name: thesis_gpu
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia
  - defaults
dependencies:
  - archspec=0.2.3
  - biopython=1.83
  - boltons=23.1.1
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.27.0
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - conda=23.11.0
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - distro=1.9.0
  - filelock=3.13.1
  - fmt=10.2.1
  - fsspec=2024.2.0
  - icu=73.2
  - idna=3.6
  - jinja2=3.1.3
  - joblib=1.3.2
  - jsonpatch=1.33
  - jsonpointer=2.4
  - krb5=1.21.2
  - libabseil=20230802.1
  - libarchive=3.7.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.5.0
  - libcxx=16.0.6
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran5=13.2.0
  - libhwloc=2.9.3
  - libiconv=1.17
  - liblapack=3.9.0
  - libmamba=1.5.6
  - libmambapy=1.5.6
  - libnghttp2=1.58.0
  - libopenblas=0.3.26
  - libprotobuf=4.25.1
  - libsolv=0.7.28
  - libsqlite=3.45.1
  - libssh2=1.11.0
  - libtorch=2.1.2
  - libuv=1.47.0
  - libxml2=2.12.5
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.6
  - markupsafe=2.1.5
  - menuinst=2.0.2
  - mkl=2023.2.0
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.2.1
  - numpy=1.26.4
  - openssl=3.2.1
  - packaging=23.2
  - pandas=2.2.1
  - pip=24.0
  - platformdirs=4.2.0
  - pluggy=1.4.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.8.2
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytorch=2.1.2
  - pytorch-cuda=12.1
  - pytz=2024.1
  - readline=8.2
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.31.0
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - setuptools=69.1.1
  - six=1.16.0
  - sleef=3.5.1
  - sympy=1.12
  - tbb=2021.11.0
  - threadpoolctl=3.3.0
  - tk=8.6.13
  - tqdm=4.66.2
  - truststore=0.8.0
  - typing_extensions=4.10.0
  - tzdata=2024a
  - urllib3=2.2.1
  - wheel=0.42.0
  - xz=5.2.6
  - yaml-cpp=0.8.0
  - zstandard=0.22.0
  - zstd=1.5.5
 